export const REQUEST_LOGIN_ACTION = 'REQUEST_LOGIN_ACTION';
export const REQUEST_LOGIN_ACTION_SUCCESS = 'REQUEST_LOGIN_ACTION_SUCCESS';
export const REQUEST_LOGIN_ACTION_FAILURE = 'REQUEST_LOGIN_ACTION_FAILURE';
