name: Unit Tests with coverage

# job level conditions don't seem to work at the moment
# https://github.community/t5/GitHub-Actions/Status-of-workflows-with-no-running-jobs/td-p/37160

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-tests]')"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      if: "!contains(github.event.head_commit.message, '[skip-tests]')"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      if: "!contains(github.event.head_commit.message, '[skip-tests]')"
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      if: "!contains(github.event.head_commit.message, '[skip-tests]')"
    - run: npm run test
      if: "!contains(github.event.head_commit.message, '[skip-tests]')"
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      if: "!contains(github.event.head_commit.message, '[skip-tests]')"
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/lcov.info
